### ISSUE TITLE
problems with GPU

### ISSUE THREAD

**Issue by CLG68** [tencent-ailab/Interformer#14]
I got a problem running :

PYTHONPATH=interformer/ python inference.py -test_csv examples/demo_dock.csv \
-work_path examples/ \
-ensemble checkpoints/v0.2_energy_model \
-batch_size 1 \
-posfix *val_loss* \
-energy_output_folder $DOCK_FOLDER \
-reload \
-debug

[rank0]: Traceback (most recent call last):
[rank0]:   File "/media/christian/extra/VS/VS_Interformer/inference.py", line 128, in <module>
[rank0]:     results = collect_results_gpu(res, device=args['gpus'])
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/christian/extra/VS/VS_Interformer/inference.py", line 37, in collect_results_gpu
[rank0]:     part_tensor = torch.tensor(
[rank0]:                   ^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: invalid device ordinal
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ChatGPT that suggested this modification to inference.py script; this modification solved the problem:

**from ChatGPT:**

The error persists because the collect_results_gpu function uses the device parameter (set to args['gpus']) incorrectly. Even though CUDA_VISIBLE_DEVICES=0 limits GPU visibility, args['gpus'] = 1 causes the function to try using an invalid GPU index.

**Root Cause**

PyTorch expects GPU indices to be zero-based (0 for the first GPU). However, in the script:

    args['gpus'] = 1 is interpreted as using the second GPU (index 1), which doesn't exist in your setup (you only have one GPU).

**Solution: Fix collect_results_gpu**

Modify the collect_results_gpu function in inference.py to ensure the device parameter resolves correctly. 

**Replace this section:**

def collect_results_gpu(result_part, device='cpu'):

**with:**

def collect_results_gpu(result_part, device=None):
    if device is None or device == 'cpu' or device == 0:
        device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
    elif isinstance(device, int):
        device = f'cuda:{device - 1}'  # Adjust for zero-based indexing

This ensures:

    If args['gpus'] is 1, the function uses cuda:0.
    It falls back to the CPU if no GPUs are available or if args['gpus'] = 0.

**Comment by HoaSoup** [comment]
I have the same error on RTX A5000.

**Comment by CLG68** [comment]
If you replace, in inference.py,  this line:

def collect_results_gpu(result_part, device='cpu'):

with:

def collect_results_gpu(result_part, device=None):
if device is None or device == 'cpu' or device == 0:
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
elif isinstance(device, int):
device = f'cuda:{device - 1}' # Adjust for zero-based indexing

It should work.  At least for me, it solved the problem.

**Comment by mainguyenanhvu** [comment]
@CLG68 Thank you. I have made a pull request according to your solution: https://github.com/tencent-ailab/Interformer/pull/15
